### ISSUE TITLE
Deck file merge - Entity already exists 

### ISSUE THREAD

**Issue by cfw-cagip** [Kong/deck#1011]
Hi Guys,

I am setting up a gitlab ci pipeline that will allow publishing apis in kong.  The error message is `Error: building state: inserting route Swagger_Petstore-listPets: entity already exists`.

In my pipeline, I have to convert an openapi (oas) specification to a kong specification (this is done with the command deck file openapi2kong -s oas.yaml -o kong-spec.yaml). 
Then I make a backup of the current Kong configuration (deck dump -o current-spec.yaml) and I merge current-spec.yaml and kong-spec.yaml files to get the final file to synchronize on kong (deck file merge current-spec.yaml kong-spec.yaml -o merge-spec.yaml).

At the first occurrence of publication, it goes without a hitch. (deck diff -s merge-spec.yaml; deck sync -s merge-spec.yaml). On the other hand for all other occurrences of file merge, it does not work since the elements defining the api some already exist in kong.

So with the deck tool is it possible to do a file merge by solving the problem of duplication and prioritizing the specification to keep according to its position in the list of files provided as a parameter to deck.

Deck version : v1.25.0
Kong version : v3.2

Thanks in advance

**Comment by Tieske** [comment]
duplicate of https://github.com/Kong/go-apiops/issues/84 see discussion there.

@cfw-cagip please do not create duplicate issues, or at least cross-reference them if there is no response. Thx.
