### ISSUE TITLE
feature: add conversion from OpenAPI spec to Kong's declarative format

### ISSUE THREAD

**Issue by hbagdi** [Kong/deck#110]
This is one of the most widely requested feature from Kong's community. decK can have another command like `covert` or `render` which takes in an OpenAPI-spec file and spits out a Kong configuration file.

**Comment by teunis90** [comment]
@hbagdi why is converting necessary? Would it not be better if Kong itself would have good support for OpenApi and/or JSON Schemas?

I know currently Kong is lacking this support. I also know that in Lua it's hard to implement this feature. I got to this conclusion by 2 inactive LUA repositories on GH:
- https://github.com/jdesgats/ljsonschema
- https://github.com/tianchaijz/lua-resty-jsonschema 

However, with the new Go support in Kong 2.0 this might be possible and should be reconsidered. 

I would like to hear your thoughts on this.

**Comment by hbagdi** [comment]
This is a two part problem:
1. Kong should be able to route requests correctly and configure plugins based on a set of OAPI files.
2. Kong should be able to validate request/responses based on OAPI spec itself.

(1) has to be done using tooling external to Kong. (2) has to be done via a plugin in Kong.

**Comment by teunis90** [comment]
This sounds like a useful feature. Do you have a reference to the Kong counterpart of this issue?

**Comment by hbagdi** [comment]
No. This is how I envision the solution personally. You can create a custom
plugin to get it done.

**Comment by gauravve** [comment]
@hbagdi does decK support creation of plugins ?

**Comment by hbagdi** [comment]
> @hbagdi does decK support extension using custom plugins ?

not sure what you mean. Can you rephrase please?
