### ISSUE TITLE
unable to create rate-limit-advanced plugins at route level with deck for distributed management

### ISSUE THREAD

**Issue by vinaykumar-git6** [Kong/deck#1148]
I am from API team and my API gets deployed to EKS via pipeline.
In the same pipeline I have deck jobs to create services, routes with tags for distributed management.
All works fine until there is no dependency on any global entities like consumers, ca_cert etc.

Now the problem statement is 
When I try to create a rate limit advanced plugin on route level in same pipeline its throws error

$ deck gateway diff --kong-addr $KONG_ADMIN_URL --headers Kong-Admin-Token:$KONG_ADMIN_TOKEN --tls-skip-verify  plugin.yaml --parallelism=1 

Error: building state: consumer xyz.abc.com for plugin rate-limiting-advanced: entity not found

below is plugin.yaml
***************************************************************
_format_version: "3.0"
_workspace: PBG
_info:
  select_tags:
  - app1
plugins:        
  - config:
      limit: [50]
      namespace: WQ9PoXJUmtVl3fA0utK7ElXa7hpsAyXZL
      path: null
      redis:
        cluster_addresses:
        - pb-kong-redis-0001-001.xyz.cache.amazonaws.com:6379
        - pb-kong-redis-0002-001.xyz.cache.amazonaws.com:6379
        password: 1234QWERR
        timeout: 2000
      sync_rate: -1
      window_size: [1]
    consumer: xyz.abc.com
    enabled: true
    name: rate-limiting-advanced
    protocols:
    - http
    - https
    route: app1DeckPoc

Note: consumer 'xyz.abc.com' is created manually by logging into kmanager with no tags, 
since these are global entities it can be used by n number of applications and routes and cannot be part of any particular application state yaml file.

please advise a way to address such scenarios.
Thanks in advance

**Comment by Tieske** [comment]
This should be the same case as https://github.com/Kong/deck/pull/1124 right? @AntoineJac

**Comment by AntoineJac** [comment]
@Tieske  confirm it is indeed the same case than #1124

**Comment by vinaykumar-git6** [comment]
Thanks for the information.
can you please tell when "  default_lookup_tags:" feature will be release for customers to fully leverage advantage of deck

**Comment by rspurgeon** [comment]
cc @teb510 for visibility

**Comment by mheap** [comment]
`default_lookup_tags` has shipped
