### ISSUE TITLE
Release Schedule?

### ISSUE THREAD

**Issue by danielpoonwj** [Kong/deck#1151]
Hi all,

Thank you maintainers for the hard work and constant improvements to this tool and ecosystem!

I was just wondering if there is a release schedule or cadence we can refer to. There are some bug fixes in `main` that would fix some issues in our workflow. Our workaround is building from source for now but it would be great to use released artefacts

**Comment by mheap** [comment]
Hey @danielpoonwj - We're working on a release schedule for deck now. Our intention is to release every 2 weeks if there are changes on `main`
