### ISSUE TITLE
OpenAPI 3.1 support for `deck file` commands

### ISSUE THREAD

**Issue by mheap** [Kong/deck#1324]
The `deck file openapi2kong` currently uses `kin-openapi` for all it's OpenAPI requirements. This library does not support OpenAPI 3.1, which is a requirement from users.

This issue is to replace `kin-openapi` with https://github.com/pb33f/libopenapi, ensuring that there are no changes in the tests. This should be a transparent update for our users.

**Comment by Prashansa-K** [comment]
@mheap Could you clarify what all features from OpenAPI 3.1 initiative have we decided to adopt/support?

**Comment by Prashansa-K** [comment]
To elaborate, I wanted to properly understand what is the entire scope of this task.
After the library update, what features from 3.1 are we keeping in the scope?

**Comment by mheap** [comment]
@Prashansa-K Existing functionality should continue to work when present with an OpenAPI 3.1 format file, rather than returning an error.

Any OAS 3.1 specific functionality can be handled in a separate issue (we don't have any specific requests yet other than general 3.1 support)
