### ISSUE TITLE
Error with 2 Consumer Groups on 1 Consumer

### ISSUE THREAD

**Issue by mheap** [Kong/deck#1384]
> Deck gateway sync and deck gateway diff gives an error while syncing more than 1 consumer groups to a single consumer. The problem started from version 1.39.2 onwards as it was working fine in 1.36.1 version. Error is listed as below

**Analysis**

Looks like it was introduced in 1.39.2.https://github.com/Kong/deck/compare/v1.39.1...v1.39.2 The corresponding go-database-reconciler update: https://github.com/Kong/go-database-reconciler/compare/v1.12.2...v1.13.0 It's likely this commit https://github.com/Kong/go-database-reconciler/commit/c5193585c3f8060eaebe749529493d25bfaf0958 , but I don't know enough.

**Acceptance Criteria**

- [ ] `deck sync` works with two consumer groups attached to a single consumer

**Comment by Prashansa-K** [comment]
@mheap Could you clarify which gateway versions would support this? Is this needed by only >= 3.4.x?

**Comment by mheap** [comment]
Yes, 3.4+ only
