### ISSUE TITLE
deck file kong2kic default use Ingress API, not Gateway API

### ISSUE THREAD

**Issue by yeVoker** [Kong/deck#1427]
[v1.41.0](https://github.com/Kong/deck/releases/tag/v1.41.0)
deck file kong2kic -s kong-config.yaml -o gateway.yaml Converted to Ingress API

**Comment by dichico** [comment]
same as here! It broke our pipelines :(

please fix this, we reverted for 1.40.x version.

**Comment by battlebyte** [comment]
This issue is fixed in [release 1.42.0](https://github.com/Kong/deck/releases/tag/v1.42.0)
