### ISSUE TITLE
Project's documentation site returns 404

### ISSUE THREAD

**Issue by jumal** [Kong/deck#194]
The project's documentation site mentioned in the Documentation section (https://deck.yolo42.com) returns 404

**Comment by mmorel-35** [comment]
Hello @jumal , 
I know they were planning to integrate deck's documentation as an official part of Kong's documentation, maybe the previous site has been closed to avoid having to maintain two versions.
You can find the documentation [here](https://docs.konghq.com/deck/).

**Comment by hbagdi** [comment]
I changed the default branch from `master` to `main` and that broke Github Pages. The master branch is still around but that still happened. 

This should be fixed now.
