### ISSUE TITLE
decK throws error when there is a document associated with a service

### ISSUE THREAD

**Issue by aaronhmiller** [Kong/deck#208]
Error: 400 Bad Request {"message":"an existing 'document_objects' entity references this 'services' entity","name":"foreign key violation","fields":{"@referenced_by":"document_objects"},"code":4}

To recreate:
1. in Kong Enterprise, create a service
2. associate a document (say an Open API spec that documents the service)
3. run a `deck reset`
above error will occur.

**Comment by hbagdi** [comment]
Talked to Aaron out of band to resolve this.
There is nothing decK can do about this at this moment. If in future, decK manages document objects in Kong Enterprise, we can avoid this from happening.
