### ISSUE TITLE
Add flag to avoid/skip deletion statement

### ISSUE THREAD

**Issue by marcoam** [Kong/deck#211]
There are times where I just want deck to only add/modify objects that exist in the file **without deleting objects** that exist on my live environment. Adding something like a --no-delete or --skip-deletes flag may be a good idea to avoid these kind of deletions.

**Comment by hbagdi** [comment]
Although this seems like a reasonable ask, I'm hesitant to open this door.
decK's delete feature is critical when it comes to "declarative" configuration. Without it, any additional configuration present in Kong can surprise users.

There is an alternative here. Use [distributed configuration](https://docs.konghq.com/deck/guides/distributed-configuration/). Simply add a `--select-tag` flag to your command and you won't get any deletes if the tag is unique.
