### ISSUE TITLE
Release a patch version 1.2.2

### ISSUE THREAD

**Issue by hbagdi** [Kong/deck#215]

**Comment by rainest** [comment]
Feeling out GH project management stuff: @hbagdi we've (or rather, the automation) has assigned this to ourselves. How are we selecting what issues/changes go into it? As of yet, there's no 1.2.2 milestone; when should we create that and what should we pull into it?

**Comment by hbagdi** [comment]
We generally should create a milestone when we start working towards a release. Due to current state of migration of project management, this was not tracked. We want to release all the fixes that have been put into `main` branch for 1.2.2.

**Comment by hbagdi** [comment]
The release is out.
