### ISSUE TITLE
--select-tag includes Consumer Creds when Consumer is Tagged But Creds are not

### ISSUE THREAD

**Issue by rhewittCP** [Kong/deck#217]
decK version: 1.2.1
Kong version: 2.0.3 CE

Steps to repro:
* Create a consumer and tag it "foo"
* Create a set of creds for that consumer and **do not** tag them
* Using decK dump the configuration while selecting the tag "foo"  `deck dump --select-tag foo`
* The resulting deck config file will contain the consumer credentials that are not tagged
* An attempt to sync with --select-tag foo attempts to tag the credentials with 'foo'

Usecase:
* We managed almost all the entities with deck except the credentials. The consumers managed by decK also have plugins and other consumer specific config so --skip-consumers does not work for us.

Let me know if additioanal information is needed.

**Comment by hbagdi** [comment]
This happens because tags were not previously supported for credentials in Kong. This has now changed and credentials can be made tag aware in decK:
https://github.com/Kong/deck/blob/main/dump/dump.go#L443-L444

One question: If you would like to manage consumers using decK, what is the flow of creating associated credentials in kong in your use case?

**Comment by rhewittCP** [comment]
Ahh, that makes sense. 

We create the credentials manually using Konga. The main reason we don't want to sync these creds via decK is we have our decK config checked into source control.

**Comment by hbagdi** [comment]
PR welcome to fix this.

**Comment by rhewittCP** [comment]
@hbagdi,

Awesome! I don't have time right now to work on a PR. I was able to work around this for now by re-organizing our decK config and use the --skip-consumers flag so this isn't a blocking issue for me anymore.

**Comment by shashankaholic** [comment]
@rhewittCP I was curious how did you overcome this challenge. We are in similar situation where we want to manage everything on consumers except credentials via decK. And manage credentials using Kong manager or Admin API.

**Comment by rhewittCP** [comment]
@shashankaholic,
For now we just stopped managing consumers altogether with deck. We tagged all entities we wanted to manage with deck and use the --select-tag functionality to sync only those entities. Using the tagging also ensures any previously managed consumers are not part of the deck sync.
