### ISSUE TITLE
deck requires permissions to /workspaces beyond workspace permissions

### ISSUE THREAD

**Issue by mflendrich** [Kong/deck#218]
Per @hbagdi,
> decK performs a check to make sure that the workspace exists, if tries to create it.
> The check and creation both require more privileges than the workspace super-admin grant.

As a workspace super-admin, I want to be able to operate on that workspace using deck. However, the current privilege checks disallow that. The scope of this issue is to ensure that workspace rights are enough to preform reset/sync.

```console
$ deck reset --workspace Customers --headers "Kong-Admin-Token:kong" --verbose 10
This will delete all configuration from Kong's database.
> Are you sure? y
GET /workspaces/Customers HTTP/1.1
Host: localhost:8001
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
HTTP/1.1 403 Forbidden
Content-Length: 116
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: http://localhost:8002
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 18 Sep 2020 18:40:03 GMT
Server: kong/1.5.0.5-enterprise-edition
Vary: Origin
X-Kong-Admin-Latency: 43
X-Kong-Admin-Request-Id: 54FehCuOSfkVJxJ0TxqgNVVdGLzy4Ljv
{"message":"fel@konghq.com-4071bc34-bea5-48a9-88bd-eddcb726294a, you do not have permissions to read this resource"}
Error: error when getting workspace: 403 Forbidden {"message":"fel@konghq.com-4071bc34-bea5-48a9-88bd-eddcb726294a, you do not have permissions to read this resource"}
$ 
```

**Comment by hbagdi** [comment]
@mflendrich Do you have a solution in mind on how to solve this problem?

**Comment by mflendrich** [comment]
@hbagdi
`deck reset --workspace=X`, before attempting to delete items in the workspace, performs a `GET` on `/workspaces/X`. We can solve the problem by removing this GET and proceeding with deletion straight away. If a workspace does not exist, the first of the delete operations will result in a 404 with a `message` along the lines of `workspace 'X' does not exist`.

The fix would be to:
- patch go-kong to include the message in returned errors,
- remove the GET `/workspaces/X` in the `reset` command.

**Comment by mflendrich** [comment]
Fixes mentioned above sent for review: #219, Kong/go-kong#8.

**Comment by mflendrich** [comment]
For `sync` - we could assume that the workspace creation operation is idempotent, and just create the workspace every time and treat the error ("unique constraint violation") as a confirmation that creation was a no-op.

**Comment by hbagdi** [comment]
> For sync - we could assume that the workspace creation operation is idempotent, and just create the workspace every time and treat the error ("unique constraint violation") as a confirmation that creation was a no-op.

Discussed internally. This doesn't work for the case when the user doesn't have permissions to create a workspace. We will instead use a list endpoint like `/workspaces/foo-ws/services` to test if a workspace exists or not.
