### ISSUE TITLE
deck doesn't delete "documents" entities from services

### ISSUE THREAD

**Issue by marcoam** [Kong/deck#227]
in Kong Enterprise 2.1

Reproduction Scenario: 
1) Create a service
2) Create a "Document" in the service 
3) Run `deck reset`

You should get an error: 

> Error: 400 Bad Request {"message":"an existing 'document_objects' entity references this 'services' entity","name":"foreign key violation","fields":{"@referenced_by":"document_objects"},"code":4}

**Comment by cwurm** [comment]
Same issue as https://github.com/Kong/deck/issues/208. The problem is the new document objects entities that only exist in KE and are not managed by decK.
