### ISSUE TITLE
Release v1.2.3

### ISSUE THREAD

**Issue by hbagdi** [Kong/deck#231]

**Comment by rainest** [comment]
Github and Docker updated, but Homebrew is infected by gremlins.

Travis (the CI system, not me) is also infected by gremlins. Attempted a possible CI change, but found that https://github.com/Kong/homebrew-deck/pull/1 triggered no new build on the PR. Attempting to trigger it instead by merging to master didn't work either, and attempting to trigger one manually indicates that we haven't enough Traviscoins to run it.

That appears to be the result of a billing snafu, and while we've opened a support request to try and address this, it does not appear they've answered it yet.

Asking for a status update on that and waiting. This is mostly complete, but the OS X release artifacts are stuck until CI can run again (and may be further stuck if they still don't run correctly).

**Comment by rainest** [comment]
Tracking the aforementioned failure in https://github.com/Kong/homebrew-deck/issues/2

As the install and test phases of the job work, the release appears sound even though we can't yet audit it. Closing this and following up on the CI issue separately since all artifacts are indeed published.
