### ISSUE TITLE
[Feature] - Allow the ability to mute or not display plugin config when syncing

### ISSUE THREAD

**Issue by DeclanPaulKeane** [Kong/deck#232]
**Request Feature**

Can we add the ability to mute or not display plugin or general config when syncing changes to Kong.

**Current Behaviour**

When you make any change to the configuration of Kong, the change is outputted to standard out.

**Reproduction** 

1. Create a file like below. Filename "add-header.yaml":

`_format_version: "1.1"
services:
- connect_timeout: 60000
  host: mockbin.org
  name: Test
  path: /request
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
- connect_timeout: 60000
  host: httpbin.org
  name: test
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  write_timeout: 60000
  routes:
  - name: test
    paths:
    - /some/path
    path_handling: v0
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    strip_path: true
    https_redirect_status_code: 426
  plugins:
  - name: pre-function
    config:
      access: []
      body_filter: []
      certificate: []
      functions:
      - |-
        local original_path = ngx.var.request_uri
        ngx.req.set_header("Kong-Original-Path-1", original_path)
      header_filter: []
      log: []
      rewrite: []
    enabled: true
    protocols:
    - grpc
    - grpcs
    - http
    - https
`

2. deck sync -s add-header.yaml 
3. Make a change to the config. Change "Kong-Original-Path-1" to "Kong-Original-Path-2"
4. deck sync -s add-header.yaml 
5. Changes that are outputted to the screen:

`updating plugin pre-function for service 951c1f16-79f8-48d2-9186-5e7d3a53beb9  {
   "config": {
     "access": [
     ],
     "body_filter": [
     ],
     "certificate": [
     ],
     "functions": [
     "local original_path = ngx.var.request_uri
ngx.req.set_header("Kong-Original-Path-1", original_path)"
      "local original_path = ngx.var.request_uri
ngx.req.set_header("Kong-Original-Path-2", original_path)"
     ],
     "header_filter": [
     ],
     "log": [
     ],
     "rewrite": [
     ]
   },
 "created_at": 1.605227664e+09,
   "enabled": true,
   "id": "30095a96-5186-40a1-9751-63fb902503b7",
   "name": "pre-function",
   "protocols": [
     "grpc",
     "grpcs",
     "http",
     "https"
   ],
   "service": {
     "id": "951c1f16-79f8-48d2-9186-5e7d3a53beb9"
   }
 }`

**Why add this?**

Some users who log stdout when using CI/CD tools would not like to have this displayed as it could expose sensitive information.

**Comment by hbagdi** [comment]
xref #152
