### ISSUE TITLE
sync can't support db_less mode kong

### ISSUE THREAD

**Issue by RyouZhang** [Kong/deck#235]
in db_less mode, deck sync while get code 415.

**Comment by hbagdi** [comment]
decK doesn't work with DB-less mode of Kong.
What is it that you are trying to do?
Have you looked into loading the configuration file [directly into Kong](https://docs.konghq.com/2.2.x/db-less-and-declarative-config/)?

**Comment by RyouZhang** [comment]
but use admin config api， it works well. so i think deck should support it.

**Comment by hbagdi** [comment]
Tracking this in #238. We don't have plans to get to it anytime soon.
