### ISSUE TITLE
Users not getting updates from old hbagdi/deck homebrew tap

### ISSUE THREAD

**Issue by peterskim12** [Kong/deck#236]
I didn't realize there were some new recent releases to decK because my homebrew was using the old hbagdi/deck tap. I'm sure I'm not the only one. :) 

Can we look into ways to help get users onto the new kong/deck tap? 

Thanks!

**Comment by hbagdi** [comment]
I just pushed the an update to `hbagdi/deck` tap as well. I'll continue to do this as newer versions of decK are released.
Hope that solves the issue. Please re-open if not.
