### ISSUE TITLE
v1.2.3 breaks the `--verbose 2` option

### ISSUE THREAD

**Issue by morals415** [Kong/deck#237]
There is a defect in the latest dECK version that prevents the tool from displaying the verbose response as shown below.

Before 1.2.3

deck --config deck.yaml ping --verbose 2
GET / HTTP/1.1
Host: localhost:8444
User-Agent: Go-http-client/1.1
Accept-Encoding: gzip
HTTP/1.1 200 OK
Content-Length: 15387
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: https://localhost:8445
Connection: keep-alive
Content-Type: application/json; charset=utf-8
Date: Fri, 27 Nov 2020 18:21:48 GMT
Server: kong/2.2.0.0-enterprise-edition
Vary: Origin
X-Kong-Admin-Request-Id: fbfRWCZc0N9cgUzHxvUEsm31VZTid0N3
{"plugins":{"enabled_in_cluster":[],"available_on_server":{"grpc-web":true,"graphql-rate-limiting-advanced":true,"vault-auth":true,"correlation-id":true,"pre-function":true,"request-transformer-advanced":true,"cors":true,"jwt-signer":true,"upstream-timeout":true,"rate-limiting":true,"application-registration":true,"route-transformer-advanced":true,"collector":true,"hmac-auth":true,"request-transformer":true,"response-ratelimiting":true,"oauth2-introspection":true,"zipkin":true,"loggly":true,"statsd-advanced":true,"bot-detection":true,"request-size-limiting":true,"ldap-auth":true,"azure-functions":true,"grpc-gateway":true,"rate-limiting-advanced":true,"ldap-auth-advanced":true,"response-transformer-advanced":true,"post-function":true,"oauth2":true,"response-transformer":true,"session":true,"prometheus":true,"basic-auth":true,"ip-restriction":true,"statsd":true,"jwt":true,"proxy-cache":true,"acme":true,"graphql-proxy-cache-advanced":true,"key-auth":true,"degraphql":true,"kafka-upstream":true,"http-log":true,"proxy-cache-advanced":true,"forward-proxy":true,"file-log":true,"datadog":true,"tcp-log":true,"syslog":true,"request-validator":true,"mtls-auth":true,"acl":true,"route-by-header":true,"openid-connect":true,"exit-transformer":true,"udp-log":true,"key-auth-enc":true,"aws-lambda":true,"canary":true,"kafka-log":true,"request-termination":true}},"tagline":"Welcome to kong","configuration":{"plugins":["bundled"],"portal_auth_login_attempts":0,"cassandra_read_consistency":"ONE","admin_listen":["0.0.0.0:8444 ssl"],"admin_invitation_expiry":259200,"lua_ssl_trusted_certificate"
SNIP
Successfully connected to Kong!
Kong version:  2.2.0

1.2.3

deck --config deck.yaml ping
Successfully connected to Kong!
Kong version:  2.2.0
deck --config deck.yaml ping --verbose 2
Successfully connected to Kong!
Kong version:  2.2.0

**Comment by hbagdi** [comment]
Fixed with #243
