### ISSUE TITLE
feature: support multi-document YAML

### ISSUE THREAD

**Issue by hbagdi** [Kong/deck#241]
decK can read multiple YAML files but it expects a single YAML document in each file.
This issue tracks adding in support for multiple documents in a single YAML file.

#207 took a stab at implementing this but couldn't get through because `ghodss/yaml` doesn't support multi-document YAML. Why? Because `go-yaml/yaml` doesn't support it. Why? Because:

https://github.com/go-yaml/yaml#compatibility

> The yaml package supports most of YAML 1.1 and 1.2, including support for anchors, tags, map merging, etc. Multi-document unmarshalling is not yet implemented, and base-60 floats from YAML 1.1 are purposefully not supported since they're a poor design and are gone in YAML 1.2.

It is unlikely this feature will be implemented unless the dependencies are made to support multi-document YAMLs.

**Comment by TVenuMadhav** [comment]
+1

**Comment by hbagdi** [comment]
Since multi-documents are gone from YAML 1.2 and it is unlikely that the underlying library will implement the feature of YAML, I'm going to close this feature request. When in doubt, please use multiple state files with decK to achieve the same result.
