### ISSUE TITLE
State File(s) RegExp does not limit YML, YAML, JSON to the File Extension

### ISSUE THREAD

**Issue by waciii-ra** [Kong/deck#247]
https://github.com/Kong/deck/blob/f06bf460bf133dd80af7da7881e50675dfb79b9d/file/readfile.go#L114

Because there is no dot (".") preceding the extension value, nor an End-of-String RegExp Anchor, the decK RegExp matches case-insensitive YML, YAML, JSON at any location in a file name in contrast to what is expressed in the code comments of the Blob referenced above.

**Comment by hbagdi** [comment]
#255 has a better description so closing this one.
