### ISSUE TITLE
decK analytics noticeably slow down commands which should complete fast

### ISSUE THREAD

**Issue by joanbm** [Kong/deck#253]
I recently discovered that the reason decK was slow in one of the environments I am using it in is that it's trying to send analytics to some server.

I found two major problems with the current decK analytics implementation (in addition to the ones pointed to in issue #136):

1. The analytics process will block completion of the decK process until the analytics can be sent. This is a problem because if Internet access is firewalled, any decK command could hang until the analytics timeout (3 seconds) even if it otherwise completes instantly.

2. The analytics server seems slow in general, so it will add a noticeable lag even if the analytics can be successfully sent.

The workaround I found is to disable analytics.

Logs of case 1: An environment that is firewalled and has no internet access (requests to outside servers hang):

```sh
$ docker run --rm --entrypoint='' -t kong/deck:v1.2.4 /bin/sh -c 'echo | time deck validate -s -'
real	0m 3.00s
user	0m 0.00s
sys	0m 0.00s
$ docker run --rm --entrypoint='' -e DECK_ANALYTICS=off -t kong/deck:v1.2.4 /bin/sh -c 'echo | time deck validate -s -'
real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s
```

Logs of case 2: On my local computer which has internet access

```sh
$ docker run --rm --entrypoint='' -t kong/deck:v1.2.4 /bin/sh -c 'echo | time deck validate -s -'
real	0m 0.35s
user	0m 0.00s
sys	0m 0.00s
$ docker run --rm --entrypoint='' -e DECK_ANALYTICS=off -t kong/deck:v1.2.4 /bin/sh -c 'echo | time deck validate -s -'
real	0m 0.00s
user	0m 0.00s
sys	0m 0.00s
```

Part of the problem is that the analytics server is slower than it should:

```sh
$ time curl http://d.yolo42.com/polluting_your_statistics_hahaha -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

real	0m0,352s
user	0m0,007s
sys	0m0,000s
$ time curl http://www.google.com -o /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 13851    0 13851    0     0  98935      0 --:--:-- --:--:-- --:--:-- 98935

real	0m0,146s
user	0m0,007s
sys	0m0,000s
```

**Comment by hbagdi** [comment]
@joanbm Thanks for the report. Please take a look at #254 which makes the analytics collection a best-effort only. You should not see any slow down with that patch.

> Part of the problem is that the analytics server is slower than it should:

This is network latency (depending on where you are in the world) adding up quick because of the TCP handshake.

**Comment by joanbm** [comment]
Thanks for the quick answer, I tested the patch on my local machine and it fixes the issue for me.  I can't test it in the firewalled environment until it's in an official release, but I don't see why it wouldn't work.

However, I think that with this fix "from your side" the statistics are going to be biased, for example I don't think you will see many hits for `deck validate` after this patch since it will complete faster than the HTTP request most of the time. Perhaps it this proves to be a problem you could send a single UDP datagram or something similar, though I'm not 100% sure if that'd work.

**Comment by hbagdi** [comment]
> However, I think that with this fix "from your side" the analytics are going to be biased, for example I don't think you will see many hits for deck validate after this patch since it will complete faster than the HTTP request most of the time. 

Yes, that was the reason of completing HTTP request for analytics. Since it interferes with the user experience, we are okay to make the trade-off. A good UX is one of the most important goals for this project.

> Perhaps if this proves to be a problem you could send a single UDP datagram or something similar, though I'm not 100% sure if that'd work.

It certainly does. We will have to do some re-tooling on our end and we are not ready to do that change yet.
