### ISSUE TITLE
sync with json format

### ISSUE THREAD

**Issue by lukasa1993** [Kong/deck#273]
sync command doesn't seem to support JSON format, so if i dump in json is there another way i can sync it ?

**Comment by hbagdi** [comment]
`deck sync -s your-config.json` should do it. Are you seeing any errors?

**Comment by lukasa1993** [comment]
haven't tried that was trying auto-picking file as it does for .yml will checkout that option but would prefer auto-picking

**Comment by hbagdi** [comment]
Afraid that the default for `--state` flag is `kong.yaml` so that won't be possible.
Please re-open this issue if you can't get `.json` to work.
