### ISSUE TITLE
mTLS auth endpoint bubbles up error with Enterprise free mode

### ISSUE THREAD

**Issue by rainest** [Kong/deck#274]
Enterprise images running in free/unlicensed mode return 403s for endpoints that are Enterprise-only.

`dump.GetAllMTLSAuths()` has logic to return an empty set of mTLS auth credentials when the response is a 404 (what OSS images return) but nothing for a 403, which bubbles back up to `dump.Get()` and upward: https://github.com/Kong/deck/blob/v1.4.0/dump/dump.go#L616-L622

Handling this is a bit tricky, as this endpoint can return a 403 in different situations. Either:
- Enterprise is running in free mode, and this endpoint is not available at all.
- Enterprise is running in licensed mode, but decK is using an RBAC user that lacks permissions for it.

Do we need to handle these differently? In free mode, the 403 is effectively equivalent to a 404, since the database can't possibly contain any mTLS auth entities. In licensed mode, mTLS auth entities may exist, but decK cannot see them.

Treating either type of 403 the same as a 404 in `dump.Get()` may be fine. An empty entity set isn't of much interest until you try to solve later. If you haven't asked decK to create any such entities, it should and will do nothing. If you have asked decK to create that entity type, that failure [will bubble up](https://github.com/Kong/deck/blob/v1.4.0/state/credentials.go#L81-L86), and should, as decK cannot reconcile the state.

**Comment by rainest** [comment]
From previous initial discussion with @hbagdi, we want to avoid treating 403s like 404s if possible. We could instead infer that this endpoint is unavailable from a combination of the version and license available from the root endpoint. I don't think there's any explicit free mode marker, but the license object is just absent when using it:

```
[kong-enterprise-edition-2.3.2.0-alpine:/]# export KONG_LICENSE_DATA='{}'
[kong-enterprise-edition-2.3.2.0-alpine:/]# kong start
Using Konnect Enterprise without a license
Kong started
[kong-enterprise-edition-2.3.2.0-alpine:/]# curl -s localhost:8001 | jq ".version, .license"
"2.3.2.0-enterprise-edition"
null
[kong-enterprise-edition-2.3.2.0-alpine:/]# export KONG_LICENSE_DATA='{"license":"REDACTED"}'
[kong-enterprise-edition-2.3.2.0-alpine:/]# kong restart
Kong stopped
Kong started
[kong-enterprise-edition-2.3.2.0-alpine:/]# curl -s localhost:8001 | jq ".version, .license"
"2.3.2.0-enterprise-edition"
{
  "customer": "Kong Inc",
  ...
}
```
At present I don't think we have general-purpose Enterprise/version gates in decK; this would require we build one. The Enterprise-only stuff is, AFAIK, documented as such, but ultimately we trust users not to use features (workspace creation, RBAC entities) if they're not available.

**Comment by aaronhmiller** [comment]
I just ran into this and I see another user in Kong Nation did as well: https://discuss.konghq.com/t/deck-fails-with-mtls-auths-403-error/7918

This renders Free Mode incompatible with decK until fixed.

**Comment by hbagdi** [comment]
@rainest Given the high-impact nature of this problem, let's treat 403 and 404 for this case. We want to avoid unlicensed and licensed differentiation in decK as far as possible as it unnecessarily complicates the code. In your patch, please add a comment in the code to explain a) what we are doing is bad b) why we still do it c) it MUST not be repeated anywhere else.

**Comment by rainest** [comment]
> We want to avoid unlicensed and licensed differentiation in decK as far as possible

I don't know that we can actually get away from this entirely given the way Enterprise works, where some endpoints aren't available depending on your settings, but we can do it more elegantly. IMO something along the lines of the go-kong [test feature detection](https://github.com/Kong/go-kong/blob/v0.17.0/kong/kong_test.go#L131-L170) seems appropriate. Instead of inferring this from the response code, we can check the root API endpoint to check if we're in free mode or if RBAC is disabled and make the associated decK functions return empty object sets.
