### ISSUE TITLE
Analytics are being sent to a third party

### ISSUE THREAD

**Issue by charlie-haley** [Kong/deck#275]
We were debugging issues with our pipeline and noticed decK was sending analytics to a third party domain, is it possible to disable this by default or send them over to a Kong owned domain? 

https://github.com/Kong/deck/blob/main/cmd/analytics.go#L30

**Comment by hbagdi** [comment]
We have to move this to a Kong owned demo but hasn't been prioritized in a while.

**Comment by mflendrich** [comment]
resolved by https://github.com/Kong/deck/pull/301
