### ISSUE TITLE
non-zero-ezit-code not work

### ISSUE THREAD

**Issue by Zaragon-AQ** [Kong/deck#293]
Hi, 
we are looking to develop a CI/CD for Kong that let us know if there are drifting in the configuration on kong and the one on our git repo. 
We know that there is a parameter for the the deck diff command (non-zero-ezit-code) that let us know if there is an actual difference between two yaml file. The problem is that deck is giving us false positives logging changes to 
"updated_at" 
and 
"created_at" 
and this is happening only on some services. In other services with lots of routes it detects changes only in some routes so it has also this random behavior that we don't understand.

Deck version used is 1.5.0 and we are using Kong-Enterprise

**Comment by mmorel-35** [comment]
Hello! Have you tried 1.5.1 version of Deck? 
This issue should be fixed with it

**Comment by hbagdi** [comment]
Correct. This should be fixed with v1.5.1. Please re-open if otherwise.
