### ISSUE TITLE
Document --select-tag in --help and how to bypass prompt on `reset` usage?

### ISSUE THREAD

**Issue by aaronhmiller** [Kong/deck#323]
Was just about to test `deck reset --select-tags <foo>` running within a shell script but is there no way to pass `-y` flag to avoid the prompt?

Also, there currently isn't any doc for `--select-tag` in --help...so that would be really nice to have!

**Comment by mmorel-35** [comment]
I don't think - y is going to work. According to https://github.com/Kong/deck/blob/58eef897f8e8189524d74d4cfc7250dcfd8cfe15/cmd/dump.go#L179, "-yes" would do the job. There might be a way to define it in your HOME/.deck.yml, but I don't know yet how

**Comment by aaronhmiller** [comment]
found ` -f, --force` which will do part two

**Comment by GGabriele** [comment]
Hi @aaronhmiller , https://github.com/Kong/deck/commit/0c31abb3ff79d69736ec23a5613c7b36340f6cbb added several docs improvement, including a clearer explanation for `--selec-tag` as well.

```
$ deck reset --help
The reset command deletes all entities in Kong's database.string.

Use this command with extreme care as it's equivalent to running
"kong migrations reset" on your Kong instance.

By default, this command will ask for confirmation.

Usage:
  deck reset [flags]

Flags:
      --all-workspaces        reset configuration of all workspaces (Kong Enterprise only).
  -f, --force                 Skip interactive confirmation prompt before reset.
  -h, --help                  help for reset
      --rbac-resources-only   reset only the RBAC resources (Kong Enterprise only).
      --select-tag strings    only entities matching tags specified via this flag are deleted.
                              When this setting has multiple tag values, entities must match every tag.
...
...
```
