### ISSUE TITLE
Automatically generate command line reference documentation

### ISSUE THREAD

**Issue by hbagdi** [Kong/deck#345]
Docs on docs site are usually out of date.
Automate the generation of reference docs using https://github.com/spf13/cobra/blob/master/doc/md_docs.md.

**Comment by hbagdi** [comment]
cc @Kong/team-docs

**Comment by hbagdi** [comment]
Closed by mistake.

**Comment by lena-larionova** [comment]
FYI for whoever works on this issue, I'm happy to help figure out the markdown formatting for the output.

**Comment by hbagdi** [comment]
@lena-larionova So I took a stab at this with #382.
- You will need to install [Go](https://golang.org/) the machine where you want to generate the docs.
- Clone this repo
- run `make generate-cli-docs` and you will have docs generated in `docs/cli-docs` directory in the repo.

Let me know what you think.

**Comment by lena-larionova** [comment]
I'm way too slow at noticing github notifications, ack. Thanks for putting this together - I'll take a look and then help build on top of what you've created.
