### ISSUE TITLE
Sanitize leading and trailing slashes when concatenating URLs

### ISSUE THREAD

**Issue by mflendrich** [Kong/deck#390]
Today deck expects that the admin API URL does not end with a trailing slash. Otherwise it will construct endpoint URLs incorrectly.

The scope of this issue is to ensure that all URL operations are safe and won't yield incorrect results if the operands come from the user (at least the admin url) with trailing slashes.

Acceptance criteria:
- [x] `--kong-addr` accepts URLs both with and without trailing slashes

**Comment by ccfishk** [comment]
@mflendrich just check, do you think this issue is still valid ?

**Comment by mflendrich** [comment]
Verification performed against current `main` 29c690e969556fb41e65b572924dc24bee9559c1:

```
./deck dump --kong-addr https://127.0.0.1:8444 --tls-skip-verify
./deck dump --kong-addr https://127.0.0.1:8444/ --tls-skip-verify
```

Both commands ran successfully. The issue seems to be resolved.

**Comment by mflendrich** [comment]
resolved "already working as intended"
