### ISSUE TITLE
Codecoverage CI issues

### ISSUE THREAD

**Issue by shaneutt** [Kong/deck#433]
Seeing some CI failures for Codecov, the purpose of this issue is to take a look and see if we can't sort those out:

https://github.com/Kong/deck/runs/2764177615?check_suite_focus=true#step:7:53

**Comment by mmorel-35** [comment]
It seems deck is not the only one concerned, see [thisstackoverflow question from yesterday](https://stackoverflow.com/questions/67861379/codecov-fails-in-github-actions)

**Comment by shaneutt** [comment]
@hbagdi I don't have the repository permissions required to fix this, would you mind adding the CI env please? :bow:

**Comment by shaneutt** [comment]
All set now :+1:
