### ISSUE TITLE
deck dump --select-tag X doesn't dump linked plugins

### ISSUE THREAD

**Issue by anton-mesnyankin** [Kong/deck#456]
Hello,

deck 1.7.0 'dump' command with '--select-tag' option exports only objects that have a tag, 
but not linked objects (plugins that are connected to a service/route (I have checked for ip-restriction and jwt plugins)). 
I think that this is core functionality, because plugins don't allow tags + exporting part of service/route configuration (wo plugins) doesn't have a lot of sense?

I tried a workaround - adding required plugins to a state file, but
"deck diff" shows that plugins need to be created
"deck sync" fails on plugin creating step (UNIQUE violation detected on ....)

We are using terraform with kong, deck looks very interesting, but I couldn't get it working as terraform replacement yet (issue above is one of reasons).

**Comment by anton-mesnyankin** [comment]
Am I trying to use deck in some strange way?

**Comment by elazar** [comment]
@anton-mesnyankin I don't think you are; I'm experiencing this issue too. Same deck version.

**Comment by elazar** [comment]
I ended up writing a bash script to work around this that seems to work.

This script saves the plugins per service or route to a local filesystem path similar to that of the API request path (e.g. so you can maintain them under version control), then reads plugin data from those files file and pushes it the Admin API using [`curl`](https://curl.se/).

See related docs for Admin API endpoints to [list](https://docs.konghq.com/gateway-oss/1.5.x/admin-api/#plugin-object) or [update](https://docs.konghq.com/gateway-oss/1.5.x/admin-api/#update-route) plugins.

The script looks something like the sample below. If you prefer using YAML, it should be possible to tweak this to use something like [`yq`](https://github.com/mikefarah/yq).

```bash
# Admin API base URL; see https://docs.konghq.com/gateway-oss/1.5.x/admin-api/ for port information
addr="http://$host:8001"

# Local directory where plugin information will be written to and read from
plugins_dst="$PWD/kong"

# Path to local jq executable with some default flags; see https://github.com/stedolan/jq/
jq="path/to/jq -r -M -c"

# Path to local deck JSON dump
file="path/to/deck-dump.json"

# Functions to get route and service identifiers from the local dump using jq

get_route_ids () {
    $jq < $file '.services | .[] | .routes | .[] | .id' | tr ' ' "\n"
}

get_service_ids () {
    $jq < $file '.services | .[] | .id' | tr ' ' "\n"
}

# Function to write plugin dumps to the local filesystem

write_plugins () {
    local entity="$1"
    local entity_id="$2"
    local plugin_dst="$plugins_dst/$entity/$entity_id/plugins.json"
    [ -d "$plugin_dst" ] || mkdir -p `dirname "$plugin_dst"`
    curl -s "$addr/$entity/$entity_id/plugins" > $plugin_dst
}

# Function to push local plugin dumps to the Admin API

update_plugins () {
    local entity="$1"
    local entity_id="$2"
    local plugins=`$jq < "$plugins_dst/$entity/$entity_id/plugins.json" '.data | .[]'`
    [ -z "$plugins" ] || echo "$plugins" | while read plugin; do
        local plugin_id=`echo "$plugin" | $jq '.id'`;
        curl -v -X PUT \
            -H 'Content-Type: application/json' \
            --data-raw "$plugin" \
            "$addr/$entity/$entity_id/plugins/$plugin_id";
    done
}

# To write plugins for both routes and services to the local filesystem:

for route_id in $(get_route_ids); do
    write_plugins 'routes' "$route_id";
done

for service_id in $(get_service_ids); do
    write_plugins 'services' "$service_id";
done

# To push local plugin dumps for both routes and services to the Admin API:

for route_id in $(get_route_ids); do
    update_plugins 'routes' "$route_id";
done

for service_id in $(get_service_ids); do
    update_plugins 'services' "$service_id";
done
```

**Comment by GGabriele** [comment]
This is the expected behaviour: whenever tags are used, it's expected that they are added accordingly to all entities.

```
$ deck dump --yes --select-tag managed-by-deck

$ cat kong.yaml
_format_version: "1.1"
_info:
  defaults: {}
  select_tags:
  - managed-by-deck
services:
- connect_timeout: 60000
  host: mockbin.org
  name: svc1
  plugins:
  - config:
      per_consumer: false
    enabled: true
    name: prometheus
    protocols:
    - http
    - https
  port: 80
  protocol: http
  read_timeout: 60000
  retries: 5
  tags:
  - managed-by-deck
  write_timeout: 60000
```

Closing this. Feel free to reopen or comment back if you have any more doubts or questions.
