### ISSUE TITLE
deck konnect commands do not honor --headers flag

### ISSUE THREAD

**Issue by rainest** [Kong/deck#468]
Originally reported internally in FTI-2727.

Some Konnect test/development environments have additional authentication requirements (specifically basic-auth) beyond the Konnect login system.

The `--headers` flag should be able to add the additional auth headers, but cannot, as konnect commands just ignore it. We need to review how we [add headers to the client configuration](https://github.com/Kong/deck/blob/v1.7.0/cmd/root.go#L178) for other commands and make it apply to konnect commands also.

**Comment by hbagdi** [comment]
https://github.com/Kong/deck/commit/6cf2b011d98bdc11928df41db6827ce904805622 fixes this one
