### ISSUE TITLE
Deck 1.8.0 fails to create workspace

### ISSUE THREAD

**Issue by cwurm** [Kong/deck#491]
With deck 1.8.0 when trying to sync to a new workspace I now get an error message:
```bash
$ deck sync -s kong.yaml --workspace NewWorkspace
Warning: Workspace 'NewWorkspace' specified via --workspace flag is different from workspace '' found in state file(s).
Error: snis: HTTP status 404 (message: "Workspace 'NewWorkspace' not found")
```

I saw the workspace check was refactored in https://github.com/Kong/deck/pull/385 - maybe it's related to that? I haven't looked into it any closer.

**Comment by rainest** [comment]
See https://github.com/Kong/kong/issues/7554 and this bit of code used by the refactor: https://github.com/Kong/go-kong/blob/d8debeb1a98c797ea1013244efcbb71022abed1c/kong/exists.go#L11

We thought HEADs worked one way in Kong, and they do if the entity does exist, but not if they don't. They will eventually work that way, but I expect you'd like support for this below Kong 2.7. With pending changes from https://github.com/Kong/go-kong/pull/90 on Kong 2.5:

```
11:04:57-0700 yagody $ go get github.com/kong/go-kong@add-checkingws-api 
go: downloading github.com/kong/go-kong v0.21.1-0.20210922175908-a053d604d371
go get: upgraded github.com/kong/go-kong v0.21.0 => v0.21.1-0.20210922175908-a053d604d371
11:05:32-0700 yagody $ go build -v -gcflags=all="-N -l" -ldflags "-X main.RELEASE=$TAG -X main.COMMIT=$COMMIT -X main.REPO=$REPO_INFO" -o /tmp/bdeck
github.com/kong/go-kong/kong/custom
github.com/kong/go-kong/kong
github.com/kong/deck/utils
github.com/kong/deck/dump
github.com/kong/deck/state
github.com/kong/deck/file
github.com/kong/deck/types
github.com/kong/deck/convert
github.com/kong/deck/diff
github.com/kong/deck/cmd
github.com/kong/deck
11:05:38-0700 yagody $ /tmp/bdeck sync -s /tmp/ttt.yaml                                                                                             
creating workspace ttt
creating service httpbin2
creating route test2
Summary:
  Created: 2
  Updated: 0
  Deleted: 0
```

**Comment by rainest** [comment]
@cwurm 1.8.1 is out with a library bump that should fix this. Let me know if it didn't and I'll figure out what I screwed up.

**Comment by cwurm** [comment]
@rainest Thanks, 1.8.1 seems to have fixed it.
