### ISSUE TITLE
Deck creates only one workspace and put all services and routes inside it

### ISSUE THREAD

**Issue by mkopeyka** [Kong/deck#506]
I use `decK v1.8.2 (b538f70)` and `kong-ee:v1.5.0.1-alpine`

I created 3 test workspaces via kong ui and added 1 service and 1 route to each of them. After that I created a dump with key `--all-workspaces` so deck created 3 files (one per workspace).
[auth.yaml.txt](https://github.com/Kong/deck/files/7349480/auth.yaml.txt)
[nondeck.yaml.txt](https://github.com/Kong/deck/files/7349481/nondeck.yaml.txt)
[unifiedlogin.yaml.txt](https://github.com/Kong/deck/files/7349482/unifiedlogin.yaml.txt)
    
    ls -la deck/config/
    total 20
    drwxr-xr-x 2 maxim maxim 4096 жов 15 00:20 .
    drwxr-xr-x 3 maxim maxim 4096 жов 11 16:27 ..
    -rwxr-xr-x 1 maxim maxim  496 жов 15 00:07 auth.yaml
    -rwxr-xr-x 1 maxim maxim  496 жов 15 00:18 nondeck.yaml
    -rwxr-xr-x 1 maxim maxim  498 жов 15 00:18 unifiedlogin.yaml
    

I deleted old database to test decK on fresh empty DB. I expected this command will create 3 new workspaces
    
    deck sync --state deck/config --kong-addr http://localhost:8001 --select-tag deck
    
But it creates only first workspace and adds all services and routes to this workspace
    
    creating workspace auth
    creating service ul-service
    creating service non-deck-service
    creating service auth-service
    creating route auth-route
    creating route non-deck-route
    creating route ul-route
    Summary:
      Created: 6
      Updated: 0
      Deleted: 0

**Comment by GGabriele** [comment]
Now deck explicitly fail when attempting to sync in such conditions: https://github.com/Kong/deck/pull/576
