### ISSUE TITLE
Error:  (root): Additional property _transform is not allowed on decK sync

### ISSUE THREAD

**Issue by denissignoretto** [Kong/deck#510]
I'm using deck 1.8.2 and latest kong OSS version 2.6.0 in DB-less mode.
After pulling down the default YAML declarative definition, that just include the 2 following directives, decK fail synching with the error: 

Error: reading file: validating file content: 1 errors occurred:
        (root): Additional property _transform is not allowed

------------------------------ This is my kong.yaml ------------------

```
_format_version: "2.1"

# _transform is optional, defaulting to true.
# It specifies whether schema transformations should be applied when importing this file
# as a rule of thumb, leave this setting to true if you are importing credentials
# with plain passwords, which need to be encrypted/hashed before storing on the database.
# On the other hand, if you are reimporting a database with passwords already encrypted/hashed,
# set it to false.

_transform: true

# Each Kong entity (core entity or custom entity introduced by a plugin)
# can be listed in the top-level as an array of objects:

# ...


...

**Comment by rainest** [comment]
Ref https://docs.konghq.com/gateway-oss/2.6.x/db-less-and-declarative-config/#the-declarative-configuration-format

I don't believe we need to do anything with this for deck: our changes go through the admin API and have no way of bypassing the encryption transforms; `true` is de facto the only option we have.
