### ISSUE TITLE
deck sync creates consumers even with --skip-consumers 

### ISSUE THREAD

**Issue by tillkolter** [Kong/deck#532]
Hi,
we observed that deck creates consumers even if the `--skip-consumers` flag is enabled. Is this wanted behaviour? 

In our case that would be wanted as we want to have a one-off creation of the anonymous consumer. I just would like to get confirmation that this is not a bug.

**Comment by GGabriele** [comment]
Hi @tillkolter ,

thanks for raising this! From what I can tell, this smells like a bug. I'll double-check internally and I'll work on a fix ASAP!
