### ISSUE TITLE
Multiple kong.yaml files

### ISSUE THREAD

**Issue by satyam-bala** [Kong/deck#533]
I have multiple micro-services, each manages its own kong.yaml file.
ServiceA --> kong-a.yaml
SerivceB --> kong-b.yaml

using deck sync - replacing the other service from Kong.
how to use Deck to keep the existing service/routes, when sync new service configurations.

**Comment by rainest** [comment]
deck always fully reconciles state (if an entity exists in Kong but not in the state file, deck will always delete it), but you can specify multiple state files in a single sync:

```
deck sync -s kong-a.yaml -s kong-b.yaml
```

https://docs.konghq.com/deck/1.8.x/guides/multi-file-state/

If you need to sync the states independently of one another, you can use entity tags, and instruct deck to only operate on entities with those tags: https://docs.konghq.com/deck/1.8.x/guides/distributed-configuration/

I'll go ahead and close this, but if you still have additional questions, respond back and we'll reopen it.
