### ISSUE TITLE
Missing Docker Image for `1.8.2`

### ISSUE THREAD

**Issue by ingvaldlorentzen** [Kong/deck#540]
Hi, 

Deck `1.8.2` was released in September which fixes #495, but the latest image on DockerHub is `1.8.1` 

Is it possible to get a Docker image with version `1.8.2` ?

**Comment by hbagdi** [comment]
@rajkong Please ping @rainest internally for help to fix this.

**Comment by rainest** [comment]
Checking out `v1.8.2` and  following https://github.com/Kong/deck/blob/accefdd1b2fde43a098a2fc9611003a2cfa4a703/RELEASE.md#docker-release will fix this, minus permissions. @hbagdi o we ever intend to end support for the registry under your account?

**Comment by rajkong** [comment]
I have pushed v1.8.2 to  kong/deck:v1.8.2 and docker pull kong/deck:latest

**Comment by rainest** [comment]
Per conversation with Harry, we'll deprecate the hbagdi repo after this version. I've pushed the v1.8.2 image to it.
