### ISSUE TITLE
Update to logr 1.x

### ISSUE THREAD

**Issue by rainest** [Kong/deck#547]
Similar to https://github.com/Kong/kubernetes-ingress-controller/issues/2045. Breaking changes mean we can't upgrade without changes to our code.

**Comment by hbagdi** [comment]
@GGabriele please work with @rainest on this one.

**Comment by rainest** [comment]
See https://github.com/Kong/kubernetes-ingress-controller/issues/2072#issuecomment-995334293

There isn't actually anything to do here in decK, or in anything that we own, for that matter. At this point, it's entirely stuck on needing updates in 3rd-party deps (Knative libs). We're considering doing a PR to Knative since there's no indication they're working on it yet, but once that's done the only decK work is to bump the code-generator library version.

**Comment by rainest** [comment]
We have found a way to bypass the Knative issue: https://github.com/Kong/kubernetes-ingress-controller/pull/2105

@GGabriele bumping k8s.io/code-generator to its latest version will take care of this for deck.

**Comment by GGabriele** [comment]
Solved in https://github.com/Kong/deck/pull/565
