### ISSUE TITLE
decK uses the wrong default for strip_path

### ISSUE THREAD

**Issue by Benny-Git** [Kong/deck#555]
## Issue description

decK v0.4.0 changed the default for `strip_path` to be `false`. The default for Kong however is for the default to be `true`.
I would argue that decK simply should not set a default, and leave the value empty if not explicitly set by the user.

The original issue (which introduced this change) was about not being able to set the value to `false` at all.
Unfortunately the fix for this also changed the default value to false.

The description in the commit reads
> ```
> Breaking change:
> 
> This is a limitation of how we fill in default values for the missing
> values. It is not possible in Go to determine if a value is nil vs a
> zero vaule (false for boolean).
> ```

Is there any other way to fix this?
This issue broke our Kong db-less to db-based migration, as the yaml configs imported via decK suddenly observed a different default behavior.

## Links

- [Changelog entry for v0.4.0](https://github.com/Kong/deck/blob/main/CHANGELOG.md#v040)
- [Original issue that caused this change](https://github.com/Kong/deck/issues/18)
- [Original pull request](https://github.com/Kong/deck/pull/19)
- [Documentation about strip_path property](https://docs.konghq.com/gateway-oss/2.5.x/proxy/#the-strip_path-property)
- [Documentation about strip_path default](https://docs.konghq.com/gateway-oss/2.5.x/admin-api/#request-body-3)

**Comment by GGabriele** [comment]
https://github.com/Kong/deck/pull/573 solved this.

Default behaviour (`true`):
```
$ cat kong.yaml
services:
- name: svc1
  host: mockbin.org
  routes:
  - name: r1
    paths:
    - /r1

$ deck sync
Summary:
  Created: 0
  Updated: 0
  Deleted: 0

$ http :8001/routes/r1 | jq .strip_path
true
```

Setting it to `false`:

```
$ cat kong.yaml
services:
- name: svc1
  host: mockbin.org
  routes:
  - name: r1
    paths:
    - /r1
    strip_path: false

$ deck sync
updating route r1  {
   "https_redirect_status_code": 426,
   "id": "3b93896c-a7ba-4824-b8ee-43f2479fa077",
   "name": "r1",
   "path_handling": "v0",
   "paths": [
     "/r1"
   ],
   "preserve_host": false,
   "protocols": [
     "http",
     "https"
   ],
   "regex_priority": 0,
   "request_buffering": true,
   "response_buffering": true,
   "service": {
     "id": "850eed3e-d0f4-451d-b885-b4873989d097"
   },
-  "strip_path": true
+  "strip_path": false
 }

Summary:
  Created: 0
  Updated: 1
  Deleted: 0

$ http :8001/routes/r1 | jq .strip_path
false
```
