### ISSUE TITLE
Error: tags specified in the state file and via --select-tags flag are different. when using more than one config file

### ISSUE THREAD

**Issue by michaelhsk** [Kong/deck#561]
Kong Version 2.7
Deck Version 1.10.0

When using deck sync with --select-tag with multiple yaml files containing select_tags (always the samte tag "deck-managed" used in command) i get the error

Error: tags specified in the state file and via --select-tags flag are different.
                                        decK expects tags to be specified in either via flag or via state file.
                                        In case both are specified, they must match

If i use the command  only with one of the files everything works fine.

With deck 1.8.2 no problems with the same config/commands.

f.g. 
config for file1.yaml - file10.yaml contains tag deck-managed
```
...
_info:
  select_tags:
  - deck-managed
...
```

command: 
  deck sync --select-tag deck-managed -s /config
OR
  deck sync --select-tag deck-managed -s /config/file1.yaml -s /config/file2.yaml

produces the error

if i remove parameter from command 
"deck sync -s /config"
-> everything works as expected

same if i use only 1 file with parameter
deck sync --select-tag deck-managed -s /config/file1.yaml
deck sync --select-tag deck-managed -s /config/file2.yaml
...

or if i use parameter in command line and remove 
following lines  from yaml files
_info:
  select_tags:
  - deck-managed
...

no error.

Maybe that this bug come in with this change in v.1.9.0 ?:
1beef01 fix(sync) apply --select-tag to new entities

**Comment by GGabriele** [comment]
As stated in the [docs](https://docs.konghq.com/deck/1.8.x/guides/distributed-configuration/#sync), you don't need to use `--select-tag` with `sync` when the tag information is already in the state files, as `sync` will already use that/those.

Also, always from the docs:

> It is strongly advised that you do not supply select-tags to sync and diff commands via flags. This is because the tag information should be part of the declarative configuration file itself in order to provide a practical declarative file. The tagging information and entity definitions should be present in one place, else an error in supplying the wrong tag via the CLI can break the configuration.

That said, deck shouldn't error out like it's doing in this spot.

**Comment by GGabriele** [comment]
Fixed via https://github.com/Kong/deck/pull/571
