### ISSUE TITLE
Malformed YAML results in empty config set

### ISSUE THREAD

**Issue by rainest** [Kong/deck#578]
Syncing [test2.yaml.txt](https://github.com/Kong/deck/files/7989062/test2.yaml.txt) will not sync any of the entities listed: it will instead build a zero-entity target content from the file and delete everything.

The accidental leading spaces at the beginning of the metadata blocks cause this for an unknown reason. We should determine exactly why this occurs and instead abort with a warning instead of proceeding with the sync.

**Comment by GGabriele** [comment]
Apparently this is a problem with the underlying `yaml` library: https://go.dev/play/p/G-0WrngkEoi

I guess what we can do is have a check like this when the file is read:

```
func hasLeadingSpace(fileContent string) bool {
	if fileContent != "" && string(fileContent[0]) == " " {
		return true
	}
	return false
}
```
