### ISSUE TITLE
Deck no longer creates workspace with deck sync --workspace flag

### ISSUE THREAD

**Issue by dmortim** [Kong/deck#601]
Prior to deck 1.11. We could run the following command to create a new workspace as we applied our statefiles. 
```
deck sync --workspace some-new-workspace -s state-files ... 
```

Now we receive the error
```
retrieve schema for services from Kong: HTTP status 404(message: "some-new-workspace" not found).
```

Is there a way we can create the workspace without using the admin API? Either through deck or through Kong declarative files? 

edit: 
Environment 
Kong Hybrid EE 2.7.1.1
Openapi -> inso CLI -> deck 

Thanks, 

btw, love the 1.11 update for injecting plugin defaults. Great work

**Comment by GGabriele** [comment]
Hi @dmortim , happy to hear you like the new features! :)

I'm not currently able to reproduce your issue:

```
$ deck version
decK v1.11.0 (4235c73)

$ deck ping
Successfully connected to Kong!
Kong version:  2.7.1.1-enterprise-edition

$ deck sync --workspace test
Warning: Workspace 'test' specified via --workspace flag is different from workspace '' found in state file(s).creating workspace test
creating service svc1
Summary:
  Created: 1
  Updated: 0
  Deleted: 0
```

What happens if you add a `_workspace: some-new-workspace` entry in your state file? Do you have any RBAC in place? Does the issue go away if you switch to an older version of decK but with the same exact environment?

**Comment by dmortim** [comment]
Hi @GGabriele, your are correct. Deck Sync Creates the workspace. 

We identified the root cause of the issue. We are now getting an error code 1 when we run a deck diff against a workspace that does not exist - and hence that error I put above. Previously, we would get an error code 0 if the workspace did not exist and it would list the changes to be made, including creating the new workspace. Is this the expected behavior? 

``` bash
$ deck diff --workspace test
Warning: Workspace 'test' specified via --workspace flag is different from workspace '' found in state file(s).
creating workspace test
Error: building state: creating defaulter: get defaults for services: retrieve schema for services from Kong: HTTP status 404 (message: "Workspace 'test' not found)

$ echo $?
1
```


Thanks

**Comment by GGabriele** [comment]
PR has been merged. It will be included in the next release!
