### ISSUE TITLE
Why auto add `consumers: null` in the plugins ?

### ISSUE THREAD

**Issue by guinan34** [Kong/deck#610]
i use deck dump and then deck diff it shows , why it auto add consumers:null to every plugins ?
because the custom plugin has not the config.consumers so when i `deck sync ` will return the error below .

![image](https://user-images.githubusercontent.com/16395409/157797945-b002b3dd-7e9c-432c-bbef-f7da6ce14beb.png)
![image](https://user-images.githubusercontent.com/16395409/157798048-59d496a8-df78-43cb-86c9-919f2b655c2c.png)

**Comment by GGabriele** [comment]
Hi @guinan34 , I've been able to reproduce your issue and I'm proposing a patch for this [here](https://github.com/Kong/go-kong/pull/143). Let's wait for that to get in.

**Comment by GGabriele** [comment]
Solved [here](https://github.com/Kong/go-kong/pull/145). It will be included in the next release!
