### ISSUE TITLE
deck sync --rbac-resources-only doesn't add back actions for the role permissions

### ISSUE THREAD

**Issue by pmutyala** [Kong/deck#621]
deck version
decK v1.11.0 (4235c73)

1. Take a backup of rbac resources 
2022-03-18 15:10:20 [8] [INFO] helpers.commands cmd from generate_deck_dump_rbac_cmd is deck dump --rbac-resources-only --all-workspaces --headers "kong-admin-token: xxxxxx" --kong-addr http://kube-kong-admin.service.intraiad1.devconsul.csnzoo.com --format yaml --tls-skip-verify

cat demospace.yaml
_format_version: "1.1"
_workspace: demospace
rbac_roles:
- endpoint_permissions:
  - actions:
    - read
    endpoint: '*'
    negative: false
    workspace: demospace
  name: demospace-workspace-readonly

<img width="1274" alt="Screen Shot 2022-03-18 at 3 20 24 PM" src="https://user-images.githubusercontent.com/11222961/159070371-bc3d59fd-b473-438e-a01d-a9f50abfc54e.png">

2. delete the role 
<img width="1214" alt="Screen Shot 2022-03-18 at 3 21 29 PM" src="https://user-images.githubusercontent.com/11222961/159070487-d2a427ce-ac15-46a7-88b4-e8954dacaa94.png">

3. Restore the role through deck sync

deck sync --workspace demospace --rbac-resources-only --kong-addr http://kube-kong-admin.service.intraiad1.devconsul.service.com --headers 'kong-admin-token:{{token}}' --tls-skip-verify -s /wayfair/data/codebase/backups/20220318141020/rbac/demospace.yaml
creating rbac-role demospace-workspace-readonly
creating rbac-endpoint-permission eff2e4aa-0fb6-4df0-938a-4a2c12aaa44d-demospace-*
Summary:
  Created: 2
  Updated: 0
  Deleted: 0

4. Check role and permissions
<img width="1322" alt="Screen Shot 2022-03-18 at 3 23 07 PM" src="https://user-images.githubusercontent.com/11222961/159070716-e5f1935e-a1b8-47e2-81f2-5bddfdaa3f16.png">
5. actions is an empty array it doesn't configure anything..

If we need to edit and add back action, Kong doesn't allow and have to delete the whole permission and add it back with required actions.

**Comment by GGabriele** [comment]
Hi @pmutyala , thanks for opening this issue.

I already opened a couple of PRs for this, so hopefully we should solve this soon! 

https://github.com/Kong/deck/pull/619

**Comment by GGabriele** [comment]
Fixed this [here](https://github.com/Kong/deck/pull/619). It will be included in the next release!
