### ISSUE TITLE
deck not adapted to creating a grpc service

### ISSUE THREAD

**Issue by halfbaked** [Kong/deck#631]
**Deck Version**
decK kong/deck:v1.11.0 (4235c736640833aeb02a6f866ae7753aee47f21d) 

**The service definition in yaml:**

```
- host: myservice.com
  name: myservice
  protocol: grpc
  port: 00000
```

**The error seen:**
failed conditional validation given value of field 'protocol'; path: value must be null

**Notes**
It appears to me that the kong server rejects the request because deck provides a default value for path of "/".
Using curl to create the service will succeed.

**Comment by GGabriele** [comment]
Hi @halfbaked ,

what Kong version are you using? It seems to work fine with `2.7.0`

```
$ deck version
decK v1.11.0 (4235c73)

$ deck ping
Successfully connected to Kong!
Kong version:  2.7.0.0-enterprise-edition

$ deck sync
creating service myservice
Summary:
  Created: 1
  Updated: 0
  Deleted: 0

$ http :8001/services/myservice
{
    "ca_certificates": null,
    "client_certificate": null,
    "connect_timeout": 60000,
    "created_at": 1648709160,
    "enabled": true,
    "host": "myservice.com",
    "id": "35a6699c-0227-4370-8a9d-222b86750264",
    "name": "myservice",
    "path": null,
    "port": 0,
    "protocol": "grpc",
    "read_timeout": 60000,
    "retries": 5,
    "tags": null,
    "tls_verify": null,
    "tls_verify_depth": null,
    "updated_at": 1648709160,
    "write_timeout": 60000
}
```

**Comment by halfbaked** [comment]
Thanks for looking into this. Looking at my yaml file again, I see that the path had been set to / in the default block for all services. Taking it out and it works well. A nice-to-have improvement would be to be able to set `path: null` for a particular service (causes a validation error), but Deck is a great tool as is. Thanks for your time, and keep up the good work!
