### ISSUE TITLE
Add support for consumer_groups

### ISSUE THREAD

**Issue by etienne-napoleone** [Kong/deck#637]
Currently dumping kong config for a workspace doesn't include consumer_groups (groups themselves, consumer group memberships, etc) 

There is a note in the [documentation](https://docs.konghq.com/gateway/2.8.x/admin-api/consumer-groups/examples/#main):

> Note: Consumer groups are not supported in declarative configuration with decK. If you have consumer groups in your configuration, decK will ignore them.

But it's not clear why

**Comment by GGabriele** [comment]
Hi @etienne-napoleone,

> But it's not clear why

No specific reason, we just have to spend cycles to implement it. That's currently on our to-do list!

**Comment by etienne-napoleone** [comment]
ah sweet! sounded a bit like it was not considered/possible.

I guess no ETA?
For us it's really complicated to work in a multi-environment gitops type setup with kong enterprise and not be able to backup/restore that in a declarative way

**Comment by GGabriele** [comment]
No ETA yet, but I'm going to prioritize it now. I'll keep you posted on this issue!

**Comment by programmer04** [comment]
I think it can be closed as completed since consumer groups are the first class citizens [v1.26.0](https://github.com/Kong/deck/releases/tag/v1.26.0). WDYT @GGabriele?
