### ISSUE TITLE
support for generate, lint and dryrun in deck

### ISSUE THREAD

**Issue by pmutyala** [Kong/deck#653]
Hello, 

We started adopting to deck to do configuration backups and restore and in our CD system for our developers to publish there upstream on the gateways, was wondering if its in consideration to add support  for 
1. generate (where we generate skeleton files (yaml/json) for create services/routes/plugins/roles etc 
2. given an external file which is constructed can we lint, i see there is validate option would that suffice?
3. deck does similar stuff to what some user have been writing terraform kong providers for e.g .
     ```
     required_providers {
    kong = {
      source  = "kevholditch/kong"
      version = "6.5.0"
    }
  }
  ```
  it would be useful to have a dryrun similar to what terraform does to validate what is being changed. I see there is deck diff option to show difference between local file and target db, but sync and diff seem to have same behaviour i.e it diff creates/updates the objects rather than saying what will be changed. 

Can we propose feature requests in deck to support above options?

**Comment by GGabriele** [comment]
Hi @pmutyala ,

1. do you mean running something like `deck generate` and that would spit out a sample config file with all the resources? If so, I believe our documentation is a better place to find such examples.
2. `deck validate` makes sure your configuration file is in the proper shape. If you run it with the `--online` flag, it will also make sure the resources don't violate any schema
3. what do you mean with this? `sync and diff seem to have same behaviour i.e it diff creates/updates the objects rather than saying what will be changed. ` diff doesn't perform any change and it's the equivalent of a dry-run (if you run `deck diff` multiple times, it will always return the same results)

```
$ deck diff
updating route r1  {
-  "https_redirect_status_code": 301,
+  "https_redirect_status_code": 302,
   "id": "23e08689-6933-48d8-b7e9-293cda7bba38",
   "name": "r1",
   "path_handling": "v0",
   "paths": [
     "/r1"
   ],
   "preserve_host": false,
   "protocols": [
     "http",
     "https"
   ],
   "regex_priority": 0,
   "request_buffering": true,
   "response_buffering": true,
   "service": {
     "id": "31124ce1-07d5-4732-b968-b7e6c6c2223c"
   },
   "strip_path": true
 }

Summary:
  Created: 0
  Updated: 1
  Deleted: 0
```

**Comment by pmutyala** [comment]
thanks @GGabriele yes, i mean i don't see any option in deck to generate sample configuration files, i see examples in the docs https://docs.konghq.com/gateway/latest/install-and-run/docker/#prepare-your-configuration-file but what i am looking for is a template dump, the only way i see to mock a new configuration is to do `deck dump --workspace default` and construct using it rather looking for `deck generate --workspace default` which will dump a basic file with all required fields and optional with empty values.

**Comment by hbagdi** [comment]
Having a sub-command to generate a skeleton is a fair ask! Let's create an issue for it @GGabriele.
I'm not sure about the dry-run feature that you ask for @pmutyala. 
`deck diff` will tell you the entities that will be created or deleted (exactly like terraform plan). What am I missing?

**Comment by hbagdi** [comment]
Can we close this issue? I think we have captured all the feedback.

**Comment by GGabriele** [comment]
I think so, we will track the `generate` use case in a separate issue https://github.com/Kong/deck/issues/658

Please feel free to comment back if you have other questions/doubts!
