### ISSUE TITLE
Remove port as a restricted default field for service

### ISSUE THREAD

**Issue by dancallaghan** [Kong/deck#655]
I was just wondering the reasoning behind making port a restricted default field for services? We currently have `protocol: https` set as the default for our service, however we can't set `port: 443` as a default as it is listed as a restricted field.

Related PRs/Issues:
* #613
* #421

**Comment by GGabriele** [comment]
Hi @dancallaghan ,
This has been fixed and released in `v.1.14.0`.

Sorry for the delay!
