### ISSUE TITLE
Reset created entities on error of deck sync

### ISSUE THREAD

**Issue by dyeske61283** [Kong/deck#664]
**Feature Request**

We are using deck in our CI/CD pipelines and every time deck sync fails, it leaves the state incomplete and therefore most times the state is useless or faulty and needs to be reset manually.
Instead, it would be nice, if deck would rollback any changes it made, when an error occurs.

**Comment by hbagdi** [comment]
`deck` gives you all the tool to make this possible but doesn't have the feature baked in because rollback means slightly different to different people.
If you are using decK with Git and CI, then you could do a git revert and run `deck sync` again, which will roll back any created entities.
