### ISSUE TITLE
consumers.0.oauth2_credentials.0: redirect_uris is required

### ISSUE THREAD

**Issue by mkopeyka** [Kong/deck#684]
Hi,

I'm using Kong `2.8.0.0-ee` with decK `v1.12.1` and I faced with strange issue when I did `deck diff` command:
    
    deck diff -s default.json --kong-addr https://kong-api-dev.mykong.com
    
I saw a lot of error messages like this:
    
    consumers.0.oauth2_credentials.0: redirect_uris is required
    
The `default.json` dump file has been created right before diff command i.e. `deck` created bad file or diff logic contains some bugs.

**Comment by GGabriele** [comment]
Hi @mkopeyka , can you please include a sample config file to help us reproduce this?

**Comment by mkopeyka** [comment]
Please let me know if I have to add additional configs
    
    {
      "_format_version": "1.1",
      "_workspace": "default",
      "services": [...],
      "consumers": [
        {
          "id": "a903b747-xxxx-4238-zzzz-59b8220ceab5",
          "username": "qwerty",
          "tags": [
            "sid_is_absent"
          ],
          "oauth2_credentials": [
            {
              "id": "b6b36778-xxxx-48d6-zzzz-98a5262ef3ef",
              "name": "Product",
              "client_id": "3EAmmDxxxxxxxxxxxxxygaFEa",
              "client_secret": "1mZzzzzzzzzzzzzzT5iMa",
              "hash_secret": false
            }
          ]
        },
        {
          "id": "f51e89a6-xxxx-4394-zzzz-5d4fea7e0c63",
          "username": "ytrewq",
          "tags": [
            "sid_is_absent"
          ],
          "oauth2_credentials": [
            {
              "id": "1825ea85-xxxx-42ba-zzzz-af534433a3fd",
              "name": "Report",
              "client_id": "mEVThcxxxxxxxxxxxxxxxxp7Ea",
              "client_secret": "CMXTzzzzzzzzzzzzzzzzlIZdQIa",
              "hash_secret": false
            },
            {
              "id": "495e231a-xxxx-455e-zzzz-b32c68c77509",
              "name": "Report 2",
              "client_id": "wcx4xxxxxxxxxxxxxx4eB4a",
              "client_secret": "feGvzzzzzzzzzzzzzzzzz9K4g8u8a",
              "hash_secret": false
            }
          ]
        }
      ],
      "plugins": [...],
      "upstreams": [...],
      "certificates": [...]
    }

**Comment by GGabriele** [comment]
Thanks for reporting this! I just opened a PR to fix this.
https://github.com/Kong/deck/pull/688
