### ISSUE TITLE
Diff error - add defaults to plugin: no 'config' field found in schema

### ISSUE THREAD

**Issue by mkopeyka** [Kong/deck#697]
Hi,

I'm using Kong `2.8.0.0-enterprise-edition` with decK `v1.12.2`. 
I have these errors in case I use `deck diff` with json file with plugins but target kong doesn't have such workspace yet.
    
    creating workspace Reporting
    Error: building state: add defaults to plugin 'jwt': no 'config' field found in schema
    
    creating workspace Reporting
    Error: building state: add defaults to plugin 'cors': no 'config' field found in schema
    
    creating workspace Reporting
    Error: building state: add defaults to plugin 'prometheus': no 'config' field found in schema

**Comment by GGabriele** [comment]
Hi @mkopeyka , thanks for opening this issue.

Would you mind sharing a config file with the portion causing this problem?

**Comment by mkopeyka** [comment]
sure, `Reporting` workspace shouldn't exist in your `kong`:
    
    {
      "_format_version": "1.1",
      "_workspace": "Reporting",
      "services": [
        {
          "connect_timeout": 60001,
          "host": "host.example.com",
          "id": "f16f9d5f-2335-46ed-bfcb-677162f9bb4d",
          "name": "example",
          "port": 80,
          "protocol": "http",
          "read_timeout": 60000,
          "retries": 5,
          "write_timeout": 60000,
          "enabled": true
        }
      ],
      "plugins": [
        {
          "id": "5b04c4ab-b9b0-4dfe-af2e-89bd9b7a3256",
          "name": "cors",
          "config": {
            "credentials": false,
            "exposed_headers": null,
            "headers": null,
            "max_age": null,
            "methods": [
              "GET",
              "HEAD",
              "PUT",
              "PATCH",
              "POST",
              "DELETE",
              "OPTIONS",
              "TRACE",
              "CONNECT"
            ],
            "origins": null,
            "preflight_continue": false
          },
          "enabled": true,
          "protocols": [
            "grpc",
            "grpcs",
            "http",
            "https"
          ]
        },
        {
          "id": "e7603d7c-12ea-41f0-8b1f-4e55237c8f18",
          "name": "prometheus",
          "config": {
            "per_consumer": false
          },
          "enabled": true,
          "protocols": [
            "grpc",
            "grpcs",
            "http",
            "https"
          ]
        }
      ]
    }

**Comment by hbagdi** [comment]
@GGabriele Can this be closed?
