### ISSUE TITLE
Sync : Delete entities before creation ?

### ISSUE THREAD

**Issue by mmorel-35** [Kong/deck#698]
When we change the names of some entities (most of the time consumers) we receive some 409 conflict errors.
The root cause seems to be that the creation of the entities happen before their deletion.

What we usually do is manual deletion before running the deck sync on those entities.

**Comment by GGabriele** [comment]
Hi @mmorel-35, would you mind providing some sample config and steps to make sure we reproduce on our end exactly what you are seeing?
