### ISSUE TITLE
Deck validate is looking for a local Kong Gateway instance, despite passing konnect flags

### ISSUE THREAD

**Issue by dyeske61283** [Kong/deck#716]
**Bug**

The commands exectuted:
- deck validate --online --konnect-addr https://us.api.konghq.com --konnect-runtime-group-name default --state Desktop/konnect-dump.yml
- deck validate --online --konnect-runtime-group-name default --state Desktop/konnect-dump.yml

I have a file with Konnect user credentials saved in the default location ~/.deck.yaml

The error message:
Error: building state: creating defaulter: get defaults for services: retrieve schema for services from Kong: making HTTP request: Get "http://localhost:8001/schemas/services": dial tcp [::1]:8001: connect: connection refused

Deck is clearly trying to retrieve schema information from a local Kong Gateway instance, despite me passing Konnect flags.
According to this documentation page these settings should be sufficient:
https://docs.konghq.com/deck/latest/guides/konnect/

For the sync, diff and ping commands this works as intended.

**Comment by dyeske61283** [comment]
Hi,

```
$ deck version
decK v1.13.0 (86ca2c4) 

$ deck validate --online --konnect-addr https://us.api.konghq.com --konnect-runtime-group-name default --state Desktop/konnect-dump.yml
Error: building state: creating defaulter: get defaults for services: retrieve schema for services from Kong: making HTTP request: Get "http://localhost:8001/schemas/services": dial tcp [::1]:8001: connect: connection refused
```

**Comment by GGabriele** [comment]
I see the problem. I opened [this](https://github.com/Kong/deck/pull/718) to fix it.

**Comment by GGabriele** [comment]
The PR has been merged, I'm closing this now.
In summary: this feature is still not available with Konnect, so decK now errors out with a clear message when the user attempts to use it.
