### ISSUE TITLE
docker arm image

### ISSUE THREAD

**Issue by lukasa1993** [Kong/deck#739]
hello please add `linux/arm64/v8` docker image

**Comment by hbagdi** [comment]
If you happen to have the bandwidth for a contribution, we would gladly accept it.
This will require changes to our build pipeline: https://github.com/Kong/deck/blob/main/.github/workflows/release.yaml

**Comment by lukasa1993** [comment]
> If you happen to have the bandwidth for a contribution, we would gladly accept it.
> This will require changes to our build pipeline: https://github.com/Kong/deck/blob/main/.github/workflows/release.yaml

between line 71 and 72 add `platforms: linux/amd64,linux/arm64,linux/arm/v7`  this thats it

**Comment by hbagdi** [comment]
Do you think you can send us a PR for that?
