### ISSUE TITLE
Kong 3.0 is using new version of declaritive config

### ISSUE THREAD

**Issue by StarlightIbuki** [Kong/deck#746]
Deck is exporting config saying the config is of `_format_version` 1.1, while actually, it's exporting 3.0.

The difference: a route in 1.1 `/regex/.+` should be `~/regex/.+` in 3.0.

Please refer to: https://github.com/Kong/kong/blob/master/CHANGELOG.md#deployment:~:text=Kong%20will%20no%20longer%20use%20an%20heuristic%20to%20guess%20whether%20a%20route.path%20is%20a%20regex%20pattern.

**Comment by Hayk-S** [comment]
https://konghq.atlassian.net/browse/FT-3320

**Comment by GGabriele** [comment]
Solved in https://github.com/Kong/deck/pull/753
