### ISSUE TITLE
decK new release 1.15.X connectivity issue with Kong Konnect (Helium)

### ISSUE THREAD

**Issue by CharlesDevo** [Kong/deck#763]
Hello team,

From previous version of decK (1.14), we use to interact with Kong Konnect with command :

`deck <cmd> --kong-addr $KONNECT_ADDRESS --konnect-token $KONNECT_TOKEN`
Where, `$KONNECT_ADDRESS` = https://cloud.konghq.com

Using ping cmd: 
With decK 1.15 and 1.15.1 : `Error: reading Kong version: invalid character '<' looking for beginning of value`
With decK 1.14 : `Successfully Konnected as <user-name> (<org-name>)!`

Full pipeline was working as expected. We are not able to use --konnect-addr flag because this one hencing error : Error: authenticating with Konnect: `HTTP status 404 (message: "<failed to parse response body: invalid character '<' looking for beginning of value>")`

Thanks

**Comment by GGabriele** [comment]
Hi @CharlesDevo ,

the flag you'd want to use when running against Konnect is `--konnect-addr`, not `--kong-addr`. So the full command would look like this:

```
deck <cmd> --konnect-addr $KONNECT_ADDRESS --konnect-token $KONNECT_TOKEN
```

Can you please verify that this works well for you?

**Comment by CharlesDevo** [comment]
Hi @GGabriele,

Thanks for your reactivity.

trying `deck ping --konnect-addr https://cloud.konghq.com --konnect-token <my-token>`
With 1.15.X and 1.14.0
`Error: authenticating with Konnect: HTTP status 404 (message: "Cannot POST /api/auth")`

I also tried with different auth method using `--konnect-email` and `--konnect-password`, used credential and token have org admin role.
And for **--kong-addr** `deck <cmd> --kong-addr $KONNECT_ADDRESS --konnect-token $KONNECT_TOKEN` with **deck 1.14** throw `Successfully Konnected as <user-name> (<org-name>)!`

**Comment by GGabriele** [comment]
You're using the wrong address for Konnect, the right value is `https://us.api.konghq.com`, which is also the default value in decK.

Basically, you can simply run `deck ping --konnect-token <my-token>`:

```
$ deck ping --konnect-token $KONNECT_TOKEN
Successfully Konnected as Gabriele Gerbino (Kong)!
```

Apologies for the confusion!
https://docs.konghq.com/deck/latest/guides/konnect/

**Comment by CharlesDevo** [comment]
Thanks for your answer, I confirm this is working as expected with `https://us.api.konghq.com`. We will migrate to EU region asap, could yo confirm that we will need to use `https://eu.api.konghq.com` ?
You don't need to apologize, I'm the one who apologizes for the confusion, I seemed to have tried with `https://us.api.konghq.com` before but it didn't work.

Thanks a lot for yout help.

**Comment by GGabriele** [comment]
No apologies needed on either sides then :P 

Yes, I confirm `https://eu.api.konghq.com` is the address you want to use for Konnect in EU.

Thanks for using decK and Konnect!
