### ISSUE TITLE
Failed to use environment variable if they have % in the beginning.

### ISSUE THREAD

**Issue by nareshtank** [Kong/deck#769]
We have a random secret generator, generates the secret with % in the beginning like '%abcd@123'. We are setting this secret value in environment  variable to consumed by kong. 
During kong seed sync via deck, the command (`deck --kong-addr ${KONG_API_URL} validate -s ${KONG_SEED_TEMPLATE_PATH}`) failed with following error.

`Error: reading file: validating file content: unmarshaling file content: error converting YAML to JSON: yaml: line 46: found character that cannot start any token `

**Comment by GGabriele** [comment]
Hi @nareshtank ,

if you wrap the environment variable in quotes, then you shouldn't have any problem:

```
$ cat kong.yaml
_format_version: "3.0"
plugins:
  - name: session
    config:
      secret: "${{ env "DECK_SESSION_PLUGIN_SECRET" }}"

$ DECK_SESSION_PLUGIN_SECRET=%abcd@123 deck sync
creating plugin session (global)
Summary:
  Created: 1
  Updated: 0
  Deleted: 0

$ http :8001/plugins | jq ".data[0].config.secret"
"%abcd@123"
```

**Comment by nareshtank** [comment]
It's working in test but have to check if "" are part of the Secret string or not.

**Comment by GGabriele** [comment]
You should include the quotes within the decK file, not within the secret itself. Can't you do something like this?

```
secret: "${{ env "DECK_SESSION_PLUGIN_SECRET" }}" 
```

Or are you saying that there may be the possibility that your secret includes a quote, like `%abc"@123`? In that case, that's going to confuse most of the tooling available around, maybe you should limit the pool of allowed characters for the secret generation.

**Comment by nareshtank** [comment]
`Or are you saying that there may be the possibility that your secret includes a quote, like %abc"@123? In that case, that's going to confuse most of the tooling available around, maybe you should limit the pool of allowed characters for the secret generation.`

Yes this is my concern, I'll check and update the result here.

**Comment by GGabriele** [comment]
Closing this for now. Feel free to re-open or comment back if needed.

**Comment by nareshtank** [comment]
Thanks for your inputs, writing too late because I switched to another project. 
It's working with "" around and those are not part of the secret.
