### ISSUE TITLE
macOS DNS issues with Go <1.20

### ISSUE THREAD

**Issue by pdelre** [Kong/deck#852]
The enterprise environment (macOS + Cisco VPN + internal DNS) I work in has issues with various tools that rely on golang's native http-client (`deck`, `kubectl`, `terraform`, etc) where the DNS resolution is handled improperly when cross compiling for macOS. This has since been corrected by golang in version 1.20.

Does this project have a timeline to update from golang 1.18 to 1.20?

Quick disclaimer: I'm not a golang developer so some details above might be slightly off. As far as I know, this has been a wider community issue so I've included more detailed writeups below.

- https://danp.net/posts/macos-dns-change-in-go-1-20/
- https://github.com/golang/go/issues/12524
- https://go-review.googlesource.com/c/go/+/446178

**Comment by GGabriele** [comment]
Hi @pdelre ,

I just opened a PR to bump Go to 1.20: https://github.com/Kong/deck/pull/898

**Comment by Niranjan-K** [comment]
Bumping this thread to know when there will be a release with Go version 1.20 version

**Comment by GGabriele** [comment]
> Bumping this thread to know when there will be a release with Go version 1.20 version

This will probably happen either this week or the next.

**Comment by Niranjan-K** [comment]
@GGabriele I can see there is a tag for v1.20.0 but there is not release for it (https://github.com/Kong/deck/releases). Any plans to have the tag released this week or next?

**Comment by pdelre** [comment]
This appears resolved in [v1.21.0](https://github.com/Kong/deck/blob/main/CHANGELOG.md#v1210) and works as expected with `decK v1.23.0 (69aa892)`
