### ISSUE TITLE
Multiple DecK process running at same time

### ISSUE THREAD

**Issue by danfukuoka** [Kong/deck#855]
Hello,

The document at https://docs.konghq.com/deck/latest/guides/best-practices/ states: 

`"Always ensure that you have only one decK process running at any time. Multiple processes can conflict with each other and potentially corrupt Kong's configuration."`  

But is it still true when we use Distributed Configurations with tags that ensure updates occur in different resources of Kong?

Thanks!

**Comment by mheap** [comment]
@danfukuoka If you use the `select-tags` feature and there are no overlaps between the files, you should be ok to run syncs in parallel. The warning only applies if two `deck` processes try to control the same entity
