### ISSUE TITLE
feature request: add feature to specify default values

### ISSUE THREAD

**Issue by hbagdi** [Kong/deck#89]
As a user, I should be able to define default values for all instances of some entities, examples include:
- timeouts in service entity
- health-check and load-balancing configuration in upstream entity
- certain plugin configuraitons

**Comment by hbagdi** [comment]
We want to ensure that this feature is implement in such a way that Kong's Ingress Controller can take advantage of it.

**Comment by Tieske** [comment]
> We want to ensure that this feature is implement in such a way that Kong's Ingress Controller can take advantage of it.

What does that advantage look like?

**Comment by Tieske** [comment]
there's this in Insomnia: https://github.com/Kong/insomnia/pull/3319 , but also prior art wrt plugins etc.

How many different flows and config formats are we ending up with? This is probably oriented towards KiC? Do we have an overacrhing design of the flows we envision we need and how they relate to each other, what roles/responsibilities are where in the process?

For example: Insomnia specifically does not validate the `x-kong-<service/route/upstream>-defaults` contents, to prevent tight coupling between Insomnia versions and Kong versions.
