### ISSUE TITLE
Deck is deleting existing services after applying new changes.

### ISSUE THREAD

**Issue by abhipawar93** [Kong/deck#940]
After applying deck sync, why did the deck is deleting the existing service? 
Is there a way to avoid this? 

![image](https://github.com/Kong/deck/assets/50903530/0ed8b4c1-aac3-4c7f-ab8c-96b1d1abec47)

**Comment by Tieske** [comment]
it seems you had one called "Test1_Deck" in your file, whilst there was another one called "Deck" in the system.

Keep the name the same, and change some property, then try again.

**Comment by abhipawar93** [comment]
Hey Tieske,
It would work if I tried to edit the existing service configuration, but what I want is to create a new service without deleting existing ones.

> it seems you had one called "Test1_Deck" in your file, whilst there was another one called "Deck" in the system.
> 
> Keep the name the same, and change some property, then try again.

**Comment by abhipawar93** [comment]
Hey Tieske,
It would work if I tried to edit the existing service configuration, but what I want is to create a new service without deleting existing ones.

**Comment by abhipawar93** [comment]
Hey Tieske,
It would work if I tried to edit the existing service configuration, but what I want is to create a new service without deleting existing ones.

**Comment by GGabriele** [comment]
Hi @abhipawar93 ,

Can you please share you configuration file(s)? decK applies configuration declaratively, so if something is not present in your configuration file, then decK removes it from the running configuration.

**Comment by abhipawar93** [comment]
Hi Gabriele,

Please check below image where i have mentioned schema to create one service only without any route or plugin.

Please let me know whether the schema is correct or not.

![IMG_20230621_144319409](https://github.com/Kong/deck/assets/50903530/a9d907e2-ad49-4b8b-8feb-f173cafc3133)

**Comment by GGabriele** [comment]
Hi @abhipawar93 ,

as I mentioned before, decK applies configuration declaratively, so if something is not present in your configuration file, then decK removes it from the running configuration. 

If you want to keep both services in the running configuration, you need to include both in the configuration file.
