### ISSUE TITLE
Include ConsumerGroupConsumers field in file.Content

### ISSUE THREAD

**Issue by randmonkey** [Kong/deck#993]
In dbless mode of kong gateway, caller need to configure relationship between consumers and consumer groups in `consumer_group_consumers`, like:
```json
{
  "_format_version": "3.0",
  "consumers": [
    {
      "username": "test-consumer"
    }
  ],
  "consumer_group_consumers": [
    {
      "consumer_group": "test-consumer-group-1",
      "consumer": "test-consumer"
    }
  ],
  "consumer_groups": [
    {
      "name": "test-consumer-group-1"
    }
  ]
}
```
but now [file.Content](https://github.com/Kong/deck/blob/3e4196dc890ee20a245bc0db770f33372ce31d6e/file/types.go#L705) does not contain such a field, so we cannot configure it to Kong running in dbless mode via decK. This would block https://github.com/Kong/kubernetes-ingress-controller/issues/4448.

**Comment by mheap** [comment]
It looks as though this was resolved in KIC itself
